// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcUFcCPmQvfKdOI6HTCEhbhNyr_a4LbRA',
    appId: '1:510605352841:android:7a885d2070195d6b5ccb58',
    messagingSenderId: '510605352841',
    projectId: 'musicplayer-c4935',
    storageBucket: 'musicplayer-c4935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAESQK9UL4jTODV-ya7vS73eT2ILmHTeSE',
    appId: '1:510605352841:ios:16fa2f8c4773a1535ccb58',
    messagingSenderId: '510605352841',
    projectId: 'musicplayer-c4935',
    storageBucket: 'musicplayer-c4935.appspot.com',
    androidClientId: '510605352841-sg9o1o2d4kpuhvourr31lv9n51tlklbl.apps.googleusercontent.com',
    iosClientId: '510605352841-l1385v5omjaq8sv5gv0paa0sk7c4j0nl.apps.googleusercontent.com',
    iosBundleId: 'com.vocsy.musicpro',
  );
}
